"""
Chroma vector store wrapper.

Uses the native chromadb PersistentClient API — no LangChain wrapper.

Collections are keyed by name; the default collection for SOC evidence
embeddings is "soc_evidence".

All Chroma calls are blocking (Chroma's Python client is synchronous) so
they must be wrapped in asyncio.to_thread() when called from async code.
"""

import asyncio
from pathlib import Path
from typing import Any, Optional

import chromadb
from chromadb import Collection
from chromadb.config import Settings as ChromaSettings

from backend.core.logging import get_logger

log = get_logger(__name__)

DEFAULT_COLLECTION = "soc_evidence"


class ChromaStore:
    """
    Thin wrapper around a Chroma PersistentClient.

    Responsibilities:
    - Open / persist the Chroma database at {data_dir}/chroma.
    - Provide helpers for adding and querying documents with
      pre-computed embeddings (embeddings are generated by OllamaClient).
    """

    def __init__(self, data_dir: str) -> None:
        self._chroma_dir = str(Path(data_dir) / "chroma")
        Path(self._chroma_dir).mkdir(parents=True, exist_ok=True)

        # PersistentClient automatically persists on every mutation.
        self._client = chromadb.PersistentClient(
            path=self._chroma_dir,
            settings=ChromaSettings(anonymized_telemetry=False),
        )
        log.info("Chroma store initialised", chroma_dir=self._chroma_dir)

    # ------------------------------------------------------------------
    # Collection management
    # ------------------------------------------------------------------

    def get_or_create_collection(
        self,
        name: str = DEFAULT_COLLECTION,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Collection:
        """
        Return an existing collection or create it if absent.

        Args:
            name:     Collection name.
            metadata: Optional metadata stored with the collection
                      (e.g. embedding model name, dimension count).

        Returns:
            A Chroma Collection handle.
        """
        meta = metadata or {}
        collection = self._client.get_or_create_collection(
            name=name,
            metadata=meta,
        )
        log.debug("Collection ready", collection=name)
        return collection

    async def get_or_create_collection_async(
        self,
        name: str = DEFAULT_COLLECTION,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Collection:
        """Async wrapper around get_or_create_collection."""
        return await asyncio.to_thread(self.get_or_create_collection, name, metadata)

    # ------------------------------------------------------------------
    # Document ingestion
    # ------------------------------------------------------------------

    def add_documents(
        self,
        collection_name: str,
        ids: list[str],
        documents: list[str],
        embeddings: list[list[float]],
        metadatas: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        """
        Add documents with pre-computed embeddings to a collection.

        Args:
            collection_name: Target collection.
            ids:             Unique document IDs (must not already exist,
                             or use upsert if overwriting is intended).
            documents:       The raw text strings that were embedded.
            embeddings:      Pre-computed embedding vectors (one per document).
            metadatas:       Optional per-document metadata dicts.
        """
        collection = self.get_or_create_collection(collection_name)
        collection.upsert(
            ids=ids,
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas or [{} for _ in ids],
        )
        log.debug(
            "Documents added to Chroma",
            collection=collection_name,
            count=len(ids),
        )

    async def add_documents_async(
        self,
        collection_name: str,
        ids: list[str],
        documents: list[str],
        embeddings: list[list[float]],
        metadatas: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        """Async wrapper around add_documents."""
        await asyncio.to_thread(
            self.add_documents,
            collection_name,
            ids,
            documents,
            embeddings,
            metadatas,
        )

    # ------------------------------------------------------------------
    # Similarity search
    # ------------------------------------------------------------------

    def query(
        self,
        collection_name: str,
        query_embeddings: list[list[float]],
        n_results: int = 10,
        where: Optional[dict[str, Any]] = None,
    ) -> dict[str, Any]:
        """
        Perform a nearest-neighbour search against a collection.

        Args:
            collection_name:  Collection to search.
            query_embeddings: One or more query vectors (outer list = batch).
            n_results:        Maximum number of results per query.
            where:            Optional metadata filter dict (Chroma $eq/$in syntax).

        Returns:
            Chroma query result dict with keys:
            ids, distances, documents, metadatas, embeddings.
        """
        collection = self.get_or_create_collection(collection_name)
        kwargs: dict[str, Any] = {
            "query_embeddings": query_embeddings,
            "n_results": n_results,
            "include": ["documents", "metadatas", "distances"],
        }
        if where:
            kwargs["where"] = where

        results = collection.query(**kwargs)
        log.debug(
            "Chroma query complete",
            collection=collection_name,
            n_results=n_results,
        )
        return results

    async def query_async(
        self,
        collection_name: str,
        query_embeddings: list[list[float]],
        n_results: int = 10,
        where: Optional[dict[str, Any]] = None,
    ) -> dict[str, Any]:
        """Async wrapper around query."""
        return await asyncio.to_thread(
            self.query,
            collection_name,
            query_embeddings,
            n_results,
            where,
        )

    # ------------------------------------------------------------------
    # Admin / introspection
    # ------------------------------------------------------------------

    def list_collections(self) -> list[str]:
        """Return a list of collection names in this Chroma instance."""
        return [c.name for c in self._client.list_collections()]

    async def list_collections_async(self) -> list[str]:
        """Async wrapper around list_collections."""
        return await asyncio.to_thread(self.list_collections)

    def count(self, collection_name: str) -> int:
        """Return the number of documents in a collection."""
        collection = self.get_or_create_collection(collection_name)
        return collection.count()

    async def count_async(self, collection_name: str) -> int:
        """Async wrapper around count."""
        return await asyncio.to_thread(self.count, collection_name)

    # ------------------------------------------------------------------
    # Initialisation helper
    # ------------------------------------------------------------------

    async def initialise_default_collections(self, embed_model: str) -> None:
        """
        Ensure the default SOC evidence collection exists with correct metadata.

        Called once during application startup.
        """
        await self.get_or_create_collection_async(
            DEFAULT_COLLECTION,
            metadata={"embed_model": embed_model, "hnsw:space": "cosine"},
        )
        log.info(
            "Default Chroma collection ready",
            collection=DEFAULT_COLLECTION,
            embed_model=embed_model,
        )
