<script lang="ts">
  import { onMount } from 'svelte'
  import { api } from '../lib/api.ts'
  import type {
    IngestProvenanceRecord,
    DetectionProvenanceRecord,
    LlmProvenanceRecord,
    PlaybookProvenanceRecord,
  } from '../lib/api.ts'

  type Tab = 'ingest' | 'detection' | 'llm' | 'playbook'
  type ProvenanceRecord =
    | IngestProvenanceRecord
    | DetectionProvenanceRecord
    | LlmProvenanceRecord
    | PlaybookProvenanceRecord

  type RecentRecord = { record_id: string; record_type: string; label: string; created_at: string }

  let activeTab = $state<Tab>('detection')
  let searchId = $state('')
  let result = $state<ProvenanceRecord | null>(null)
  let loading = $state(false)
  let error = $state<string | null>(null)
  let copied = $state(false)
  let recentRecords = $state<RecentRecord[]>([])
  let recentLoading = $state(false)

  const tabLabels: Record<Tab, string> = {
    ingest: 'Ingest',
    detection: 'Detection',
    llm: 'AI Response',
    playbook: 'Playbook Run',
  }

  const tabPlaceholders: Record<Tab, string> = {
    ingest: 'Event ID',
    detection: 'Detection ID',
    llm: 'Audit ID',
    playbook: 'Run ID',
  }

  const tabTypeMap: Record<Tab, string> = {
    ingest: 'ingest',
    detection: 'detection',
    llm: 'llm',
    playbook: 'playbook',
  }

  onMount(async () => {
    await loadRecent()
  })

  async function loadRecent() {
    recentLoading = true
    try {
      const { records } = await api.provenance.recent(20)
      recentRecords = records
    } catch { /* non-critical */ }
    finally { recentLoading = false }
  }

  async function lookup() {
    if (!searchId.trim()) return
    loading = true
    error = null
    result = null
    try {
      result = await (api.provenance[activeTab] as (id: string) => Promise<ProvenanceRecord>)(searchId.trim())
    } catch (e: unknown) {
      error = (e instanceof Error ? e.message : null) ?? 'Record not found'
    } finally {
      loading = false
    }
  }

  function selectRecent(rec: RecentRecord) {
    // Map record_type → tab
    const tabForType: Record<string, Tab> = {
      ingest: 'ingest',
      detection: 'detection',
      llm: 'llm',
      playbook: 'playbook',
    }
    const tab = tabForType[rec.record_type] ?? 'detection'
    activeTab = tab
    searchId = rec.record_id
    result = null
    error = null
    lookup()
  }

  function isHash(_key: string, val: unknown): boolean {
    return typeof val === 'string' && val.length === 64 && /^[0-9a-f]+$/.test(val)
  }

  function copyHash(hash: string) {
    navigator.clipboard.writeText(hash).then(() => {
      copied = true
      setTimeout(() => { copied = false }, 1500)
    })
  }

  function fmtTime(iso: string): string {
    try {
      return new Date(iso).toLocaleString('en-US', {
        month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
      })
    } catch { return iso }
  }

  function typeIcon(t: string): string {
    if (t === 'ingest') return '📥'
    if (t === 'detection') return '🔍'
    if (t === 'llm') return '🤖'
    if (t === 'playbook') return '▶'
    return '·'
  }

  function typeColor(t: string): string {
    if (t === 'detection') return 'var(--severity-high, #f97316)'
    if (t === 'llm') return '#60a5fa'
    if (t === 'playbook') return '#a78bfa'
    return 'var(--text-muted)'
  }

  function downloadCustodyReport() {
    if (!result) return
    const report = {
      generated_at: new Date().toISOString(),
      query_tab: activeTab,
      query_id: searchId,
      provenance: result,
      _note: 'Chain-of-custody report generated by AI-SOC-Brain. Verify all SHA-256 hashes independently.',
    }
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `custody-report-${searchId.slice(0, 12)}-${Date.now()}.json`
    a.click()
    URL.revokeObjectURL(url)
  }
</script>

<div class="view">
  <!-- Header -->
  <div class="view-header">
    <div class="header-left">
      <svg width="18" height="18" viewBox="0 0 16 16" fill="none" style="color:#a78bfa">
        <path d="M3 3h10v2H3zM3 7h10v2H3zM3 11h6v2H3z" fill="currentColor" opacity="0.6"/>
        <circle cx="13" cy="12" r="2" fill="currentColor"/>
      </svg>
      <div>
        <h1>Provenance</h1>
        <p class="subtitle">Chain-of-custody audit trail</p>
      </div>
    </div>
    {#if result}
      <button class="btn-report" onclick={downloadCustodyReport} title="Download chain-of-custody JSON report">
        ⬇ Chain of Custody Report
      </button>
    {/if}
  </div>

  <div class="prov-layout">
    <!-- Left: Recent records sidebar -->
    <div class="recent-panel">
      <div class="recent-header">
        <span class="recent-title">Recent Records</span>
        <button class="refresh-btn" onclick={loadRecent} disabled={recentLoading} title="Refresh">⟳</button>
      </div>
      {#if recentLoading}
        <div class="recent-loading">Loading…</div>
      {:else if recentRecords.length === 0}
        <div class="recent-empty">No provenance records yet.</div>
      {:else}
        <div class="recent-list">
          {#each recentRecords as rec}
            <button
              class="recent-item {searchId === rec.record_id ? 'selected' : ''}"
              onclick={() => selectRecent(rec)}
              title="{rec.record_type}: {rec.record_id}"
            >
              <span class="rec-icon">{typeIcon(rec.record_type)}</span>
              <span class="rec-body">
                <span class="rec-label" style="color: {typeColor(rec.record_type)}">{rec.label || rec.record_id.slice(0, 20)}</span>
                <span class="rec-meta">{rec.record_type} · {fmtTime(rec.created_at)}</span>
              </span>
            </button>
          {/each}
        </div>
      {/if}
    </div>

    <!-- Right: Lookup + result -->
    <div class="lookup-panel">
      <!-- Tab selector -->
      <div class="tabs">
        {#each (Object.keys(tabLabels) as Tab[]) as tab}
          <button
            class:active={activeTab === tab}
            onclick={() => { activeTab = tab; result = null; error = null }}
          >{tabLabels[tab]}</button>
        {/each}
      </div>

      <!-- Search row -->
      <div class="search-row">
        <input
          type="text"
          placeholder={tabPlaceholders[activeTab]}
          bind:value={searchId}
          onkeydown={(e) => e.key === 'Enter' && lookup()}
        />
        <button class="btn-lookup" onclick={lookup} disabled={loading}>
          {loading ? 'Looking up…' : 'Lookup'}
        </button>
      </div>

      {#if error}
        <div class="error-msg">{error}</div>
      {/if}

      {#if result}
        <div class="result-header">
          <span class="result-title">Provenance Record</span>
          <button class="btn-report-inline" onclick={downloadCustodyReport}>
            ⬇ Export JSON
          </button>
        </div>
        <table class="result-table">
          <tbody>
            {#each Object.entries(result) as [key, val]}
              <tr>
                <td class="key">{key}</td>
                <td class="val">
                  {#if isHash(key, val)}
                    <span class="hash">{val as string}</span>
                    <button class="copy-btn" onclick={() => copyHash(val as string)}>
                      {copied ? '✓ Copied' : 'Copy'}
                    </button>
                  {:else if Array.isArray(val)}
                    {#if val.length === 0}
                      <span class="val-empty">—</span>
                    {:else}
                      <div class="val-list">
                        {#each val as item}
                          <div class="val-item">{item}</div>
                        {/each}
                      </div>
                    {/if}
                  {:else if val === null || val === undefined}
                    <span class="val-empty">—</span>
                  {:else}
                    {val}
                  {/if}
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      {/if}
    </div>
  </div>
</div>

<style>
  .view { display: flex; flex-direction: column; height: 100%; overflow: hidden; }

  .view-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 14px 20px;
    border-bottom: 1px solid var(--border);
    background: var(--bg-secondary);
    flex-shrink: 0;
  }
  .header-left { display: flex; align-items: center; gap: 10px; }
  h1 { font-size: 15px; font-weight: 600; margin: 0; }
  .subtitle { font-size: 11px; color: var(--text-muted); margin: 0; }

  .btn-report {
    padding: 5px 14px;
    background: rgba(167,139,250,0.15);
    border: 1px solid rgba(167,139,250,0.4);
    border-radius: 5px;
    color: #a78bfa;
    font-size: 12px;
    cursor: pointer;
    font-weight: 500;
  }
  .btn-report:hover { background: rgba(167,139,250,0.25); }

  /* Two-column layout */
  .prov-layout {
    display: flex;
    flex: 1;
    overflow: hidden;
    min-height: 0;
  }

  /* Left sidebar */
  .recent-panel {
    width: 260px;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }
  .recent-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 14px 8px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .recent-title { font-size: 11px; font-weight: 600; text-transform: uppercase; color: var(--text-muted); letter-spacing: 0.05em; }
  .refresh-btn {
    background: none; border: none; cursor: pointer;
    font-size: 14px; color: var(--text-muted); padding: 0 2px; line-height: 1;
  }
  .refresh-btn:hover { color: var(--text-primary); }
  .refresh-btn:disabled { opacity: 0.4; cursor: default; }

  .recent-loading, .recent-empty {
    padding: 16px; font-size: 12px; color: var(--text-muted); text-align: center;
  }

  .recent-list { overflow-y: auto; flex: 1; }

  .recent-item {
    width: 100%;
    display: flex;
    gap: 8px;
    align-items: flex-start;
    padding: 8px 12px;
    background: none;
    border: none;
    border-bottom: 1px solid var(--border);
    cursor: pointer;
    text-align: left;
    transition: background 0.1s;
  }
  .recent-item:hover { background: var(--bg-hover, rgba(255,255,255,0.04)); }
  .recent-item.selected { background: rgba(167,139,250,0.08); border-left: 2px solid #a78bfa; }

  .rec-icon { font-size: 13px; flex-shrink: 0; margin-top: 1px; }
  .rec-body { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
  .rec-label { font-size: 11.5px; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .rec-meta { font-size: 10px; color: var(--text-muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

  /* Right lookup panel */
  .lookup-panel {
    flex: 1;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    padding: 16px 20px;
    gap: 12px;
    overflow-y: auto;
  }

  .tabs { display: flex; gap: 6px; }
  .tabs button {
    padding: 5px 14px; border-radius: 4px;
    border: 1px solid var(--border);
    background: transparent; color: var(--text-secondary);
    cursor: pointer; font-size: 12px;
    transition: background 0.12s, color 0.12s;
  }
  .tabs button:hover { background: var(--bg-hover); color: var(--text-primary); }
  .tabs button.active { background: #a78bfa; color: #000; border-color: #a78bfa; font-weight: 600; }

  .search-row { display: flex; gap: 8px; }
  .search-row input {
    flex: 1; padding: 6px 10px;
    border-radius: 5px; border: 1px solid var(--border);
    background: var(--bg-tertiary, #111827); color: var(--text-primary);
    font-size: 12px; font-family: monospace;
  }
  .btn-lookup {
    padding: 6px 16px; border-radius: 5px; border: none;
    background: #a78bfa; color: #000; cursor: pointer;
    font-size: 12px; font-weight: 600;
  }
  .btn-lookup:disabled { opacity: 0.6; cursor: not-allowed; }

  .error-msg {
    padding: 8px 12px; background: rgba(239,68,68,0.1);
    border: 1px solid rgba(239,68,68,0.3); border-radius: 5px;
    font-size: 12px; color: #f87171;
  }

  .result-header {
    display: flex; align-items: center; justify-content: space-between;
    padding-bottom: 6px; border-bottom: 1px solid var(--border);
  }
  .result-title { font-size: 12px; font-weight: 600; color: var(--text-secondary); }
  .btn-report-inline {
    font-size: 11px; padding: 3px 10px;
    background: none; border: 1px solid var(--border);
    border-radius: 4px; color: #a78bfa; cursor: pointer;
  }
  .btn-report-inline:hover { background: rgba(167,139,250,0.1); }

  .result-table { width: 100%; border-collapse: collapse; }
  .result-table td { padding: 5px 8px; border-bottom: 1px solid var(--border); vertical-align: top; font-size: 12px; }
  .key { color: var(--text-muted); font-family: monospace; width: 200px; }

  .hash { font-family: monospace; font-size: 10px; word-break: break-all; color: var(--text-secondary); }
  .copy-btn {
    margin-left: 8px; padding: 1px 7px; font-size: 10px;
    cursor: pointer; border-radius: 3px;
    border: 1px solid var(--border); background: transparent; color: var(--text-muted);
  }
  .copy-btn:hover { color: var(--text-primary); border-color: var(--text-muted); }

  .val-empty { color: var(--text-muted); }
  .val-list { display: flex; flex-direction: column; gap: 2px; }
  .val-item { font-family: monospace; font-size: 11px; color: var(--text-secondary); }
</style>
